/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consulta_multiple;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
/**
 *
 * @author Jordy J
 */
public class CM_Ejemplo2 extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    DefaultTableModel dtm02=new DefaultTableModel();
    /**
     * Creates new form CM_Ejemplo2
     */
    public CM_Ejemplo2() {
        initComponents();
            String titulos []={"cod_ven","cod_prod","can_ven"};
            dtm02.setColumnIdentifiers(titulos);
            tbldetventa.setModel(dtm02);    
            conectar02();
            codp();
    }
    
    public void conectar02(){
        String url="jdbc:sqlserver://localhost;databaseName=ventasNoche;user="
        + "sa;password=123456;";
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con=DriverManager.getConnection(url);
            JOptionPane.showMessageDialog(rootPane, "Bienvenido", "Conectar",
            JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "No se pudo conectar a la"
            + "base de datos", "Conectar", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void mostrar(){
        String valor=(String)cbocodp.getSelectedItem();
        try{
            String sql="SELECT * FROM DetVenta WHERE cod_prod='"+valor+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            limpiar();
            while(rs.next()){
            String []datos02=new String[3];
            datos02[0]=rs.getString(1);
            datos02[1]=rs.getString(2);
            datos02[2]=rs.getString(3);
            dtm02.addRow(datos02);
            }
//            con.close();
//            stmt.close();
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        }
    }
    
    private void limpiar(){
        int filas;
        filas=dtm02.getRowCount()-1;
        for(int i=filas;i>=0;i--){
            dtm02.removeRow(i);
        }    
    }
    
    private void codp(){
        try{
            String sql="SELECT cod_prod FROM DetVenta order by cod_prod";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            while (rs.next()){
            cbocodp.addItem(rs.getString(1));
            }
//            con.close();
//            stmt.close();
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbocodp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldetventa = new javax.swing.JTable();
        btnCONSULTA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbocodp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        getContentPane().add(cbocodp, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 12, 115, -1));

        jLabel1.setText("cod_prod");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 17, -1, -1));

        tbldetventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldetventa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, 375, 111));

        btnCONSULTA.setText("CONSULTA");
        btnCONSULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCONSULTAActionPerformed(evt);
            }
        });
        getContentPane().add(btnCONSULTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 183, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCONSULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCONSULTAActionPerformed
        // TODO add your handling code here:
        mostrar();
    }//GEN-LAST:event_btnCONSULTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CM_Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CM_Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CM_Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CM_Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CM_Ejemplo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCONSULTA;
    private javax.swing.JComboBox<String> cbocodp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldetventa;
    // End of variables declaration//GEN-END:variables
}
